name: Deploy Backend to Azure

on:
  push:
    branches:
      - main  # Adjust if your deployment branch is different
  workflow_dispatch:  # Allows manual triggering
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: target/*.jar

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp deploy --resource-group toMeMailResourceGroup \
                          --name tome-mail-backend \
                          --src-path target/*.jar
